ci: validate release version (#2247)

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -36,6 +36,17 @@ jobs:
       id-token: write  # IMPORTANT: mandatory for trusted publishing
       attestations: write  # IMPORTANT: mandatory for attestations
     steps:
+      - name: Validate source branch and the version
+        shell: bash
+        env:
+          VERSION: ${{ github.event.inputs.version }}
+        run: |
+          version="$VERSION"
+          if [[ "$version" != 1.* ]]; then
+            echo "The version input '$version' is invalid. This workflow only supports versions starting with '1.'."
+            exit 1
+          fi
+
       - name: Checkout timefold-solver
         uses: actions/checkout@v6
         with:
